### ISSUE TITLE
Possessing and right-clicking with an NPC causes error

### ISSUE THREAD

**Issue by TheOnly8Z** [Dragoteryx/drgbase#11]
To replicate: Spawn a NPC with a gun (like npc_drg_testhuman), possess it, and right click. The following error will occur:
`NextBot [9][npc_drg_testhuman] Error: addons/drgbase/lua/entities/drgbase_nextbot/weapons.lua:485: attempt to index global 'wep' (a nil value)
`
This seems to happen both on HL2 weapons and weapons based off drgbase_weapon.

**Comment by Dragoteryx** [comment]
Fixed.
