### ISSUE TITLE
Something is creating script errors

### ISSUE THREAD

**Issue by JustAnRandomGuy** [Dragoteryx/drgbase#15]
Uhhh soo, i was going to play gm_construct, then i got the surprise, the sky was black, no sun, the hints doenst appear and cant open context menu...Help!

**Comment by Roachdaripper** [comment]
drgbase is a nextbot base, it isn't going to turn your game into a creepypasta.

**Comment by JustAnRandomGuy** [comment]
Uh i know, by a weird reason, it gives me script errors 😳

**Comment by Roachdaripper** [comment]
paste the script error?

**Comment by JustAnRandomGuy** [comment]
Ok, wait a little bit.

**Comment by JustAnRandomGuy** [comment]
sorry, i had to go sleep, i'll give the errors in a moment.

**Comment by JustAnRandomGuy** [comment]
[ERROR] addons/drgbase/lua/drgbase/meta/player.lua:8: attempt to call method 'GetNW2Entity' (a nil value)
1.Drg_Possesing - addons/drgbase/lua/drgbase/player.lua:8
2. DrG_IsPossesing - addons/drgbase/lua/drgbase/meta/player.lua5
3. v - addons/drgbase/lua/drgbase/possesion.lua:38
4. unknown - lua/includes/modules/hook.lua:84
[ERROR] addons/drgbase/meta/player.lua:8 attempt to call method 'GetNW2Entity' (a nil value) 1

**Comment by JustAnRandomGuy** [comment]
There.

**Comment by Dragoteryx** [comment]
Update your game. (if you are using a pirated version just buy it, the game usually goes for $1 during sales)
If the game is up to date, and you are not using a pirated version, then reinstall the game/verify the game cache.

If that still doesn't fix it, then one of your addons is causing this issue.
`ENT:GetNW2Entity` was added to the game a few years ago so the problem doesn't come from DrGBase.
If you find what addon is causing this it'd be nice if you could tell me so I can add it to the incompatible addons list.

**Comment by JustAnRandomGuy** [comment]
I need more money, in my country it is for $229 dollars.
...

**Comment by JustAnRandomGuy** [comment]
I think my sanic nextbots are causing it.
