### ISSUE TITLE
Big error

### ISSUE THREAD

**Issue by lil-tec** [Dragoteryx/drgbase#17]
With this error i cant do nothing. i cant walk, cant open context menu, sound is repeating, and npcs are like statues

[ERROR] addons/drgbase-nextbot-base/lua/drgbase/meta/player.lua:8: attempt to call method 'GetNW2Entity' (a nil value)
  1. DrG_Possessing - addons/drgbase-nextbot-base/lua/drgbase/meta/player.lua:8
   2. DrG_IsPossessing - addons/drgbase-nextbot-base/lua/drgbase/meta/player.lua:5
    3. v - addons/drgbase-nextbot-base/lua/drgbase/possession.lua:189
     4. unknown - lua/includes/modules/hook.lua:84

**Comment by lil-tec** [comment]
gmod 14.04.11

**Comment by lil-tec** [comment]
upss.. 14.07.11

**Comment by Dragoteryx** [comment]
You're using an incompatible addon or an old version of the game. (probably the latter)
