### ISSUE TITLE
Animal Mod RP Issues 

### ISSUE THREAD

**Issue by KolbaskaEU** [Dragoteryx/drgbase#18]
Hello John
When i spawn animal from this mod nextbot just freeze with this issue 
NextBot [158][drg_roach_des_penetrator] Error: lua/entities/drg_roach_ds1_base.lua:392: attempt to call method 'GetActiveWeapon' (a nil value)

This addon[Animal] very important for my server, like and DRG
P.S On Dark Souls 1 Players all fine.

https://user-images.githubusercontent.com/89182557/130020204-fdf9cc24-556a-4b5d-86da-e186d6a62b1c.mp4

https://user-images.githubusercontent.com/89182557/130020450-9514ae99-6b08-4a69-a6be-276e243c1336.mp4

sry for music, i forgot :3

**Comment by Roachdaripper** [comment]
GetActiveWeapon is a function only called on players, so whatever those animals are doing in their code it isn't good.

**Comment by KolbaskaEU** [comment]
> GetActiveWeapon is a function only called on players, so whatever those animals are doing in their code it isn't good.

But, on Dark Souls 1 Players all fine, how i can fix this, animal mod in open source, but i bad in lua.
