### ISSUE TITLE
I have problems with NPC 

### ISSUE THREAD

**Issue by MielsenReiss118** [Dragoteryx/drgbase#23]
It turns out that when I put an NPC (from Resident Evil or CoD Zombies) it turns out that when they want to chase me they get stuck in one place and never get out of that spot. 
All this happens when they want to climb a wall to overcome an obstacle but they stay there jumping and never end up moving from that same place they jump.
Another thing that happens is that when I put maps where it is not open world (that is, if it is a map where there are structures or buildings or if it is a map that is inside a house or anything, it turns out that some NPC nextboot jump and leave the map: as if they went through the wall and disappear). 
the co developer : Roach , told me that I should activate a command "drgbase_ia_climbing 0" but not only I could never find it but I get in the console that it does not exist . 
I would love if you could help me , because I can not play with any NPC of DRGBASE if it is not open map and that is something boring because I really like to play with them but they have these flaws . 
Thank you very much . 
Atte : Mielsen Reiss

**Comment by Goldermor** [comment]
I didn't find such a command (even if correct your spelling mistake).
it seems to me that the problems you describe relate more to the maps, not DrGBase itself, perhaps.
Maybe you'd better specify which addons have these problems?
