### ISSUE TITLE
DrGBase NPCs cannot be added into ZINV+.

### ISSUE THREAD

**Issue by KekkyShmekky** [Dragoteryx/drgbase#25]
I have tried to add support for them with this method to no avail.

```lua
for a, b in pairs(list.Get("DrGBaseNextbots")) do
	SpawnMenu.npcs[n] = a
	n = n + 1
end
```

**Comment by Roachdaripper** [comment]
IIRC zinv+ is incompatible anyway, as it treats all spawned npcs as snpcs, and calls functions that don't exist for nextbots

(also the error in your code is you using a not b)

**Comment by KekkyShmekky** [comment]
Okay so I applied the fix and it still doesn't let me select Nextbots from the "NPC:" field. What checks should I use to make sure ZINV+ doesn't call non-existent functions on Nextbots?

**Comment by Roachdaripper** [comment]
you'd have to edit the zinv code itself, i can't give more specific help than this because i haven't looked at the code personally, i just know that's what you gotta do

**Comment by KekkyShmekky** [comment]
[DrGBase | Nextbot Base] lua/entities/drgbase_nextbot/relationships.lua:462: attempt to index field '_DrGBaseFactions' (a nil value)
  1. IsInFaction - lua/entities/drgbase_nextbot/relationships.lua:462
   2. UpdateRelationshipWith - lua/entities/drgbase_nextbot/relationships.lua:515
    3. UpdateRelationships - lua/entities/drgbase_nextbot/relationships.lua:484
     4. unknown - lua/entities/drgbase_nextbot/shared.lua:206
      5. Spawn - [C]:-1
       6. spawnZombie - addons/zinv/lua/autorun/zinv_init.lua:468
        7. unknown - addons/zinv/lua/autorun/zinv_init.lua:352
         8. pcall - [C]:-1
          9. unknown - addons/zinv/lua/autorun/zinv_init.lua:249
          
          So I figured out something of a workaround by simply copy and pasting the NPCs' classnames into the appropriate, and after commenting out a few lines to fix some errors related to their spawning, this is the error that comes out. I can't do anything about anymore of the ZINV related lines, because I'd be preventing them from spawning NPCs entirely. The NPCs do spawn and are hostile, however.

**Comment by Roachdaripper** [comment]
> [DrGBase | Nextbot Base] lua/entities/drgbase_nextbot/relationships.lua:462: attempt to index field '_DrGBaseFactions' (a nil value)
> 
> 1. IsInFaction - lua/entities/drgbase_nextbot/relationships.lua:462
> 2. UpdateRelationshipWith - lua/entities/drgbase_nextbot/relationships.lua:515
>    3. UpdateRelationships - lua/entities/drgbase_nextbot/relationships.lua:484
>    4. unknown - lua/entities/drgbase_nextbot/shared.lua:206
>    5. Spawn - [C]:-1
>    6. spawnZombie - addons/zinv/lua/autorun/zinv_init.lua:468
>    7. unknown - addons/zinv/lua/autorun/zinv_init.lua:352
>    8. pcall - [C]:-1
>    9. unknown - addons/zinv/lua/autorun/zinv_init.lua:249
>    ```
>    So I figured out something of a workaround by simply copy and pasting the NPCs' classnames into the appropriate, and after commenting out a few lines to fix some errors related to their spawning, this is the error that comes out. I can't do anything about anymore of the ZINV related lines, because I'd be preventing them from spawning NPCs entirely. The NPCs do spawn and are hostile, however.
>    ```

this error happens when spawning nextbots and running functions on them on the same tick or something, i've had it before for different reasons, wrap the spawning function in a timer.Simple, set it to something like 0.01
