### ISSUE TITLE
How to go about using default HL2/L4D animations

### ISSUE THREAD

**Issue by Servius** [Dragoteryx/drgbase#3]
Looking to keep the pipeline for NPC creation as simple as the NPCs im trying to do. I have a functional standard Rakghoul playermodel. Id like for it to use the same animations already available on the HL2 Fast zombie. Without a recompile am I able to force the playermodel to use the zombie animations while as an npc? Is there a template for this workflow? 

My end goal is for me to have a template for what should essentially be a hl2 fast zombie with a rakghoul model and sounds instead. Doesnt need to have any extra functionality or w/.

**Comment by Servius** [comment]
I intend to repeat this process for more advanced NPCs using L4d animations. Like having a large rakhgoul use "Tank" animations from L4d.

**Comment by Servius** [comment]
Since posting this I found that the Nextbots (3.0) base has support for what Im describing. By adding this block of code: 
```
ENT.WalkAnim = ACT_HL2MP_WALK_ZOMBIE_01
ENT.FlinchWalkAnim = ACT_HL2MP_WALK_ZOMBIE_01 
ENT.CrouchAnim = ACT_HL2MP_CROUCH_ZOMBIE 
ENT.JumpAnim = ACT_HL2MP_JUMP_ZOMBIE 

ENT.MeleeAnim = ACT_GMOD_GESTURE_RANGE_ZOMBIE
```

I am able to use the desired playermodel and have it function as an npc but the the other Nextbot base doesnt perform as well and its implementation of similiar features are not up to spec with DrGBase.

**Comment by Servius** [comment]
@Dragoteryx

**Comment by Dragoteryx** [comment]
Just replace those values with the appropriate animation:
```lua
ENT.WalkAnimation = ACT_WALK
ENT.WalkAnimRate = 1
ENT.RunAnimation = ACT_RUN
ENT.RunAnimRate = 1
ENT.IdleAnimation = ACT_IDLE
ENT.IdleAnimRate = 1
ENT.JumpAnimation = ACT_JUMP
ENT.JumpAnimRate = 1
```
You can use activities or sequences.
