### ISSUE TITLE
NPC Glitch

### ISSUE THREAD

**Issue by lilratbaby** [Dragoteryx/drgbase#30]
Desc: When I spawn in the NPC's they will chase like normal until they kill me when, first, they don't give a jump scare for some reason, secondly, they get stuck on my dead ragdoll and if I try to drag the ragdoll away with the physics gun, the NPC pulls it back and does not chase me and when I get close to it, it doesn't even kill me, and at this point I have tried everything. I have tried downloading and reinstalling the mod, I have tried uninstalling my Ragdoll Mod, I have also tried at least 5 different maps to see if maybe it was the map each one with varying sizes and shapes. I will continue to search for the source of the problem, but I may need some assistance from one of the developers

**Comment by lilratbaby** [comment]
Nvm, I just fixed it

**Comment by hmzzahh** [comment]
how u fix it cus i got the glith too
