### ISSUE TITLE
no nextbot working 

### ISSUE THREAD

**Issue by reza1382** [Dragoteryx/drgbase#34]
Hey there
every time I spawn a nextbot it doesn't move or works and I have this problem with every nextbot
here is the error:

[ERROR] lua/entities/drgbase_nextbot/locomotion.lua:100: attempt to call method 'GetNextBot' (a nil value)
  1. SetDesiredSpeed - lua/entities/drgbase_nextbot/locomotion.lua:100
   2. SetSpeed - lua/entities/drgbase_nextbot/movements.lua:124
    3. UpdateSpeed - lua/entities/drgbase_nextbot/movements.lua:650
     4. unknown - lua/entities/drgbase_nextbot/shared.lua:247
     
and the drgbase menu doesn't show up
here is the error for menu error:
[ERROR] lua/drgbase/spawnmenu.lua:15: attempt to call method 'EnableSearch' (a nil value)
  1. Function - lua/drgbase/spawnmenu.lua:15
   2. unknown - gamemodes/sandbox/gamemode/spawnmenu/creationmenu.lua:42
    and use the latest version of drgbase

**Comment by Roachdaripper** [comment]
look at dis dood with his pirated gmod lmAO

**Comment by Dragoteryx** [comment]
Just buy the game.

**Comment by reza1382** [comment]
No problem 
It worked 
I updated the game 
Just to mention 
I live in iran 
If i have to buy it i have to pay a lot of money.
Sorry to waste your time
