### ISSUE TITLE
Error when interacting with non-drg nextbots

### ISSUE THREAD

**Issue by StrawWagen** [Dragoteryx/drgbase#35]
[DrGBase | Nextbot Base] lua/entities/drgbase_nextbot/relationships.lua:689: attempt to call method 'DrG_SetRelationship' (a nil value)
  1. _UpdateNPCRelationship - lua/entities/drgbase_nextbot/relationships.lua:689
   2. _SetRelationship - lua/entities/drgbase_nextbot/relationships.lua:202
    3. UpdateRelationshipWith - lua/entities/drgbase_nextbot/relationships.lua:532
     4. callback - lua/entities/drgbase_nextbot/relationships.lua:755
      5. callback - lua/drgbase/meta/entity.lua:111
       6. unknown - lua/drgbase/modules/timer.lua:4

Here's the addon that this conflicts with
https://steamcommunity.com/sharedfiles/filedetails/?id=2148063174
I just ran a local multiplayer session and spawned a drg npc, and an npc from this other base.

It looks like DRG is assuming that all nextbots are from DRG, which these guys aren't
Hope this is fixable! thanks!

**Comment by Zaurzo** [comment]
Fixed
