### ISSUE TITLE
Bug with teleport on depossess

### ISSUE THREAD

**Issue by Roachdaripper** [Dragoteryx/drgbase#4]
Tick the box, then undo the nextbot instead of leaving possession, and you get a script error that leaves the player in a limbo of sorts
-They appear invisible to other players
-They can't use weapons or a flashlight
-They are not targetted by npcs or nextbots

only killing yourself and respawning fixes it

**Comment by Dragoteryx** [comment]
Fixed. (dbfdaa8)
