### ISSUE TITLE
OnRagdoll isnt called with self

### ISSUE THREAD

**Issue by oninoni** [Dragoteryx/drgbase#43]
In Line 625 of misc.lua of the base entity the OnRagdoll Funciton isn't called with ":" but with "."
This causes no "self" being available in the function.

**Comment by Zaurzo** [comment]
To me, this looks intentional. It provides the ragdoll as the first argument, therefore, the ragdoll would be `self`.

**Comment by Zaurzo** [comment]
The function will now provide the NextBot as the third argument.
