### ISSUE TITLE
Weapon overrights npc range fields

### ISSUE THREAD

**Issue by jellyton69** [Dragoteryx/drgbase#5]
I'm thinking this was by design, but on line 115 in weapons.lua, you are overriding the NPCs variables for range config. It was incredibly annoying when I was making nextbots with weapons since the range was never being changed since your weapon range checks were overwriting it. My suggestion is just to remove code after the last *else* statement.

**Comment by Dragoteryx** [comment]
If you remove that line then weapons that do not match any of the holdtypes defined in the *_RANGE tables won't have a default range. If you don't want the range of your weapon to be overriden you need to define the range in the ENT:OnWeaponChange(oldweapon, newweapon) hook, and return true.

**Comment by jellyton69** [comment]
Ah, this function is actually very useful. Thank you!

Is this function ran on NPC spawn, when the default weapon is given?

**Comment by Dragoteryx** [comment]
Yes, the old weapon will be NULL.

**Comment by jellyton69** [comment]
Thank you very much!
