### ISSUE TITLE
Music Not Playing In Multiplayer

### ISSUE THREAD

**Issue by SonicMaster519** [Dragoteryx/drgbase#51]
Hello. Apologies if this has an obvious fix listed somewhere, but I haven't found anything of the sort and this error is slightly annoying. It appears whenever I possess a nextbot that has a music option, if I am in a multiplayer server, the music does not play. For example, let's say I possessed a nextbot and pressed the M key to begin playing music. This works fine in singleplayer, but it does not seem to work in any multiplayer servers, even if I'm hosting it and there aren't any players in said server. Once again, apologies if this has an obvious fix, but suddenly all of the nextbots I have installed that make use of music no longer do so, and I would appreciate any assistance I could get. Thanks.

**Comment by Dragoteryx** [comment]
DrGBase doesn't have built-in music support.
