### ISSUE TITLE
Why has nobody brought up the destroying doors bug?

### ISSUE THREAD

**Issue by BADCA7** [Dragoteryx/drgbase#58]
I am not convinced that nobody else has ran into this problem lately so I am surprised it hasn't been brought up. I know I have no conflicting mods, but everytime an NPC tries to break a door down my game says that said NPC is creating errors and doesn't break the door down. Rather it keeps cloning the door over and over.

Here's a code I was greeted with

[[DrgBase] The V2 Monster Pack] lua/entities/npc_drg_para_new_jumpscare.lua:313: bad argument #1 to 'SetBodyGroups' (string expected, got table)
1. SetBodyGroups - [C]:-1
2. DestroyedDoor - lua/entities/npc_drg_para_new_jumpscare.lua:313
3. CustomThink - lua/entities/npc_drg_para_new_jumpscare.lua:334
4. unknown - lua/entities/drgbase_nextbot/shared.lua:296 (x1649)

Keep in mind that the NPCs in this pack are not the only ones that are affected. I have reasonable suspicion that there is a bug in the DrGBase itself. I could be wrong but I tried everything from uninstalling every mod but this one, to verifying integrity of all files and yet the problem still persists.

**Comment by Roachdaripper** [comment]
its understandable for you to think it might be an error with drgbase itself but if you read the error, it points to the lua file npc_drg_para_new_jumpscare which is likely from this... V2 monster pack you have installed, making it an error that the mod author needs to fix

**Comment by BADCA7** [comment]
> its understandable for you to think it might be an error with drgbase itself but if you read the error, it points to the lua file npc_drg_para_new_jumpscare which is likely from this... V2 monster pack you have installed, making it an error that the mod author needs to fix

Once again, "Keep in mind that the NPCs in this pack are NOT THE ONLY ONES THAT ARE AFFECTED" meaning that it happens in every single pack. So no, It can't be the coding of the NPC pack itself. It doesn't make sense for every single SNPC pack related to DrG Base to suddenly have an error busting doors down due to an "error". I assume it could be because of Gmod's latest updates that may have caused the coding to be outdated. I have found a temporary fix in the meantime though. I have an addon called destructable doors. I will be using that until the base is updated.

**Comment by Dragoteryx** [comment]
DrGBase doesn't have built-in support for destroying doors.
